# Generated by Django 3.0.8 on 2021-01-31 00:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tags', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='stream',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 31, 0, 56, 48, 292322, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
