# Generated by Django 3.1.5 on 2021-02-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0002_auto_20210207_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
