# Generated by Django 3.1.5 on 2021-02-04 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0002_profile_favorited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favorited',
            new_name='favorites',
        ),
    ]
